
package oopa2_25.pkg26;

import javax.swing.JOptionPane;


public class ScrAddPost extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ScrAddPost.class.getName());

    /**
     * Creates new form frmAddPost
     */
    public ScrAddPost() 
    {
        initComponents();

        lblDateTime.setText(AppData.todaysDate());

        int postID = AppData.generatePostID();

        String postIDText = String.valueOf(postID);

        lblPostId.setText(postIDText);

        int userID = AppData.currentUser.getUserID();

        String userIDText = String.valueOf(userID);

        lblUID.setText(userIDText);

        rdoText.setSelected(true);
        rdoPublic.setSelected(true);

        toggleFields();
        
        //Center frames
        setLocationRelativeTo(null);
    }
    
    private void toggleFields()
    {
        boolean imageSelected = rdoImage.isSelected();

        txtName.setVisible(imageSelected);
        txtDesc.setVisible(imageSelected);
        txtLocale.setVisible(imageSelected);

        txtText.setVisible(!imageSelected);
    }
    private void clearFields()
    {
        txtName.setText("");
        txtDesc.setText("");
        txtLocale.setText("");
        txtText.setText("");

        rdoText.setSelected(true);
        rdoPublic.setSelected(true);

        toggleFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpSecurity = new javax.swing.ButtonGroup();
        bgpType = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        lblPostId = new javax.swing.JLabel();
        lblUID = new javax.swing.JLabel();
        rdoPublic = new javax.swing.JRadioButton();
        rdoPrivate = new javax.swing.JRadioButton();
        lblDateTime = new javax.swing.JLabel();
        rdoImage = new javax.swing.JRadioButton();
        rdoText = new javax.swing.JRadioButton();
        pnlImage = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        txtDesc = new javax.swing.JTextField();
        txtLocale = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnlText = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtText = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();
        lblPostID = new javax.swing.JLabel();
        lblUserID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setText("Add post");

        lblPostId.setText("lblPostId");

        lblUID.setText("lblUID");

        bgpSecurity.add(rdoPublic);
        rdoPublic.setSelected(true);
        rdoPublic.setText("Public");

        bgpSecurity.add(rdoPrivate);
        rdoPrivate.setText("Private");

        lblDateTime.setText("lblDateTime");

        bgpType.add(rdoImage);
        rdoImage.setSelected(true);
        rdoImage.setText("Image");
        rdoImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoImageActionPerformed(evt);
            }
        });

        bgpType.add(rdoText);
        rdoText.setText("Text");
        rdoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTextActionPerformed(evt);
            }
        });

        jLabel5.setText("Name:");

        jLabel6.setText("Description:");

        jLabel7.setText("Location:");

        javax.swing.GroupLayout pnlImageLayout = new javax.swing.GroupLayout(pnlImage);
        pnlImage.setLayout(pnlImageLayout);
        pnlImageLayout.setHorizontalGroup(
            pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlImageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                    .addComponent(jLabel6))
                .addGap(22, 22, 22)
                .addGroup(pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLocale, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlImageLayout.setVerticalGroup(
            pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImageLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDesc)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtLocale, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txtText.setColumns(20);
        txtText.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        txtText.setForeground(new java.awt.Color(153, 51, 255));
        txtText.setLineWrap(true);
        txtText.setRows(5);
        jScrollPane1.setViewportView(txtText);

        javax.swing.GroupLayout pnlTextLayout = new javax.swing.GroupLayout(pnlText);
        pnlText.setLayout(pnlTextLayout);
        pnlTextLayout.setHorizontalGroup(
            pnlTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTextLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlTextLayout.setVerticalGroup(
            pnlTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnSave.setText("Add Post");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnHelp.setText("Help");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        lblPostID.setText("Post ID:");

        lblUserID.setText("User ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTitle)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rdoPublic)
                                .addComponent(rdoImage)
                                .addComponent(lblPostID)
                                .addComponent(lblUserID)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoPrivate)
                            .addComponent(rdoText)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lblDateTime))
                            .addComponent(lblPostId)
                            .addComponent(lblUID)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pnlImage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnHelp)
                                .addGap(18, 18, 18)
                                .addComponent(btnSave))
                            .addComponent(pnlText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(lblDateTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPostId)
                    .addComponent(lblPostID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUID)
                    .addComponent(lblUserID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoPublic)
                    .addComponent(rdoPrivate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoImage)
                    .addComponent(rdoText))
                .addGap(7, 7, 7)
                .addComponent(pnlText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnHelp)
                    .addComponent(btnSave))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
       try
        {
            int postID = Integer.parseInt(lblPostId.getText());
            int userID = AppData.currentUser.getUserID();

            String security;

            if(rdoPublic.isSelected())
            {
                security = "Public";
            }
            else
            {
                security = "Private";
            }

            Post post;

            if(rdoImage.isSelected())
            {
                if(txtName.getText().isEmpty()
                        || txtDesc.getText().isEmpty()
                        || txtLocale.getText().isEmpty())
                {
                    JOptionPane.showMessageDialog(this, "Fill in all image fields.");
                    return;
                }

                post = new Image(
                        postID,
                        userID,
                        security,
                        txtName.getText(),
                        txtDesc.getText(),
                        txtLocale.getText()
                );
            }
            else
            {
                if(txtText.getText().isEmpty())
                {
                    JOptionPane.showMessageDialog(this, "Text post cannot be empty.");
                    return;
                }

                if(txtText.getText().length() > 300)
                {
                    JOptionPane.showMessageDialog(this, "Text cannot exceed 300 characters.");
                    return;
                }

                post = new Text(postID,userID,
                        security,txtText.getText());
            }

            AppData.addPost(post);

            JOptionPane.showMessageDialog(this, "Post added");

            clearFields();

            int newPostID = AppData.generatePostID();

            String newPostIDText = String.valueOf(newPostID);

            lblPostId.setText(newPostIDText);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
    }//GEN-LAST:event_formWindowClosing

    private void rdoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTextActionPerformed
        // TODO add your handling code here:
        toggleFields();
    }//GEN-LAST:event_rdoTextActionPerformed

    private void rdoImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoImageActionPerformed
        // TODO add your handling code here:
        toggleFields();
    }//GEN-LAST:event_rdoImageActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        AppData.scrMainMenu = new ScrMainMenu();
        AppData.scrMainMenu.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        // TODO add your handling code here:
        String helpText = "";
        helpText += "ADD POST HELP\n\n";
        helpText += "Post ID is generated automatically.\n";
        helpText += "User ID is taken from the logged-in user.\n\n";
        helpText += "Text Post:\n";
        helpText += "- Maximum 300 characters.\n\n";
        helpText += "Image Post:\n";
        helpText += "- Requires image name\n";
        helpText += "- Description\n";
        helpText += "- Location\n\n";
        helpText += "Choose Public or Private security.\n\n";
        helpText += "Click Add Post to add the post.";
        JOptionPane.showMessageDialog(this, helpText);
    }//GEN-LAST:event_btnHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ScrAddPost().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgpSecurity;
    private javax.swing.ButtonGroup bgpType;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDateTime;
    private javax.swing.JLabel lblPostID;
    private javax.swing.JLabel lblPostId;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUID;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JPanel pnlImage;
    private javax.swing.JPanel pnlText;
    private javax.swing.JRadioButton rdoImage;
    private javax.swing.JRadioButton rdoPrivate;
    private javax.swing.JRadioButton rdoPublic;
    private javax.swing.JRadioButton rdoText;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtLocale;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextArea txtText;
    // End of variables declaration//GEN-END:variables
}
