/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopa2_25.pkg26;

import javax.swing.JOptionPane;


public class ScrFriends extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ScrFriends.class.getName());

    /**
     * Creates new form frmAddFriend
     */
    public ScrFriends() {
        initComponents();
        
        //Center Frames
        setLocationRelativeTo(null);
        
        loadUsers();
        loadFriends();

        lblDetails.setText("Select a user");


    }
    
    private void loadUsers()
    {
        javax.swing.DefaultListModel<String> model =
                new javax.swing.DefaultListModel<>();

        int currentUserID = AppData.currentUser.getUserID();
        for(int index = 0; index < AppData.users.size(); index++)
        {
            User user = AppData.users.get(index);
            int userID = user.getUserID();
            if(userID != currentUserID)
            {
                String firstName = user.getFirstName();
                String surname = user.getSurname();
                String displayText =
                        userID
                        + " - "
                        + firstName
                        + " "
                        + surname;
                model.addElement(displayText);
            }
        }
        lstUsers.setModel(model);
    }
    
    private void loadFriends()
    {
        //Create model to add users
        javax.swing.DefaultListModel<String> model =
            new javax.swing.DefaultListModel<>();

        int currentUserID = AppData.currentUser.getUserID();

        for(int index = 0; index < AppData.friends.size(); index++)
        {
            Friend friend = AppData.friends.get(index);
            int storedUserID = friend.getUserID();
            if(storedUserID == currentUserID)
            {
                int friendID = friend.getFriendID();
                User user = AppData.findUserByID(friendID);

                if(user != null)
                {
                    int userID = user.getUserID();
                    String firstName = user.getFirstName();
                    String surname = user.getSurname();
                    String displayText =
                            userID
                            + " - " + firstName + " " + surname
                            + " | Added: "
                            + AppData.formatDateTime(friend.getDateTime());
                    model.addElement(displayText);
                }
            }
        }
        lstFriends.setModel(model);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstUsers = new javax.swing.JList<>();
        btnAdd = new javax.swing.JButton();
        lblDetails = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstFriends = new javax.swing.JList<>();
        btnBack = new javax.swing.JButton();
        brnRefresh = new javax.swing.JButton();
        btnFriendsPosts = new javax.swing.JButton();
        btnHelp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitle.setText("Add a friend");

        lstUsers.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstUsersValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstUsers);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblDetails.setText("lblDetails");

        jScrollPane2.setViewportView(lstFriends);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        brnRefresh.setText("Refresh");
        brnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnRefreshActionPerformed(evt);
            }
        });

        btnFriendsPosts.setText("View Friends Posts");
        btnFriendsPosts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFriendsPostsActionPerformed(evt);
            }
        });

        btnHelp.setText("Help");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdd)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(brnRefresh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHelp)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFriendsPosts)
                                .addGap(54, 54, 54))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFriendsPosts))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnBack)
                    .addComponent(brnRefresh)
                    .addComponent(btnHelp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
    }//GEN-LAST:event_formWindowClosing

    private void lstUsersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstUsersValueChanged
        // TODO add your handling code here:
        String selectedUser = lstUsers.getSelectedValue();

        if(selectedUser != null)
        {
            String[] parts = selectedUser.split(" - ");

            String userIDText = parts[0];

            int userID = Integer.parseInt(userIDText);

            User user = AppData.findUserByID(userID);

            if(user != null)
            {
                String dob = AppData.formatDate(user.getDateOfBirth());
                
                String registered = AppData.formatDateTime
                            (user.getRegisteredDate());
                        
                String details = "<html>";

                details += "User ID: " + user.getUserID() + "<br><br>";
                details += "Name: " + user.getFirstName() + " " + user.getSurname() + "<br><br>";
                details += "Email: " + user.getEmail() + "<br><br>";
                details += "DOB: " + dob + "<br><br>";
                details += "Friends: " + user.getFriendsCount() + "<br><br>";
                details += "Registered: " + registered;

                details += "</html>";

                lblDetails.setText(details);
            }
        }
    }//GEN-LAST:event_lstUsersValueChanged

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        try
        {
            String selectedUser = lstUsers.getSelectedValue();
            if(selectedUser == null)
            {
                JOptionPane.showMessageDialog(this, "Select a user first.");
                return;
            }
            String[] parts = selectedUser.split(" - ");
            String friendIDText = parts[0];
            int friendID = Integer.parseInt(friendIDText);
            AppData.addFriend(friendID);
            JOptionPane.showMessageDialog(this, "Friend added");

            loadFriends();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void brnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnRefreshActionPerformed
        // TODO add your handling code here:
        loadUsers();
        loadFriends();
    }//GEN-LAST:event_brnRefreshActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        AppData.scrMainMenu = new ScrMainMenu();
        AppData.scrMainMenu.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnFriendsPostsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFriendsPostsActionPerformed
        // TODO add your handling code here:
        try
        {
            String selected = lstFriends.getSelectedValue();

            if(selected == null)
            {
                JOptionPane.showMessageDialog(this, "Select a friend first");
                return;
            }

            String[] parts = selected.split(" - ");
            int friendID = Integer.parseInt(parts[0]);

            AppData.scrViewPosts = new ScrViewPosts(friendID);
            AppData.scrViewPosts.setVisible(true);

            this.dispose();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnFriendsPostsActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        // TODO add your handling code here:
        String helpText = "";
        helpText += "FRIENDS SCREEN HELP\n\n";
        helpText += "Users List:\n";
        helpText += "- Displays all users except yourself.\n\n";
        helpText += "Friends List:\n";
        helpText += "- Displays your current friends.\n\n";
        helpText += "Add Friend:\n";
        helpText += "- Select a user and click Add Friend.\n\n";
        helpText += "View Friend Posts:\n";
        helpText += "- Select a friend to view their posts.";
        JOptionPane.showMessageDialog(this, helpText);
    }//GEN-LAST:event_btnHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ScrFriends().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnRefresh;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFriendsPosts;
    private javax.swing.JButton btnHelp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDetails;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList<String> lstFriends;
    private javax.swing.JList<String> lstUsers;
    // End of variables declaration//GEN-END:variables
}
