/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopa2_25.pkg26;

import javax.swing.JOptionPane;

/**
 *
 * @author idiot
 */
public class ScrMainMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ScrMainMenu.class.getName());

    /**
     * Creates new form ScrMain
     */
    public ScrMainMenu() 
    {
        initComponents();
        //Center Frames
        setLocationRelativeTo(null);
        
        if(AppData.currentUser != null)
        {
            lblWelcome.setText(
                    "Welcome, "
                    + AppData.currentUser.getFirstName()
                    + " "
                    + AppData.currentUser.getSurname()
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddPost = new javax.swing.JButton();
        btnMyPosts = new javax.swing.JButton();
        btnPublicPosts = new javax.swing.JButton();
        btnFriends = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        btnHelp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAddPost.setText("Add Post");
        btnAddPost.addActionListener(this::btnAddPostActionPerformed);

        btnMyPosts.setText("View Posts");
        btnMyPosts.addActionListener(this::btnMyPostsActionPerformed);

        btnPublicPosts.setText("View Public Posts");
        btnPublicPosts.addActionListener(this::btnPublicPostsActionPerformed);

        btnFriends.setText("Friends");
        btnFriends.addActionListener(this::btnFriendsActionPerformed);

        btnExit.setText("Exit");
        btnExit.addActionListener(this::btnExitActionPerformed);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("jLabel1");

        btnHelp.setText("Help");
        btnHelp.addActionListener(this::btnHelpActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMyPosts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPublicPosts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFriends, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddPost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 155, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblWelcome)
                .addGap(18, 18, 18)
                .addComponent(btnAddPost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMyPosts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPublicPosts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFriends)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHelp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPostActionPerformed
        // TODO add your handling code here:
        AppData.scrAddPost = new ScrAddPost();
        AppData.scrAddPost.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddPostActionPerformed

    private void btnMyPostsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyPostsActionPerformed
        // TODO add your handling code here:
        AppData.scrViewPosts = new ScrViewPosts(true);
        AppData.scrViewPosts.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMyPostsActionPerformed

    private void btnPublicPostsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPublicPostsActionPerformed
        // TODO add your handling code here:
        AppData.scrViewPosts = new ScrViewPosts(false);
        AppData.scrViewPosts.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPublicPostsActionPerformed

    private void btnFriendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFriendsActionPerformed
        // TODO add your handling code here:
        AppData.scrFriends = new ScrFriends();
        AppData.scrFriends.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFriendsActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Are you sure you want to exit?");

        if(confirm == javax.swing.JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        AppData.currentUser = null;

        AppData.scrMenu = new ScrMenu();
        AppData.scrMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        // TODO add your handling code here:
        String helpText = "";

        helpText += "MAIN MENU HELP\n\n";
        helpText += "Add Post:\n";
        helpText += "Create a text or image post.\n\n";
        helpText += "My Posts:\n";
        helpText += "View your own posts.\n\n";
        helpText += "Public Posts:\n";
        helpText += "View all public posts.\n\n";
        helpText += "Friends:\n";
        helpText += "Manage friends and view friend posts.\n\n";
        helpText += "Logout:\n";
        helpText += "Return to the menu screen.";
        JOptionPane.showMessageDialog(this, helpText);
    }//GEN-LAST:event_btnHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ScrMainMenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPost;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFriends;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMyPosts;
    private javax.swing.JButton btnPublicPosts;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
