/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopa2_25.pkg26;

import javax.swing.JOptionPane;

/**
 *
 * @author idiot
 */
public class ScrViewPosts extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ScrViewPosts.class.getName());

    private int friendID = 0;
    private boolean myPosts;
    /**
     * Creates new form ScrViewPosts
     */
    public ScrViewPosts(boolean myPosts)
    {
        initComponents();

        this.myPosts = myPosts;

        this.friendID = 0;

        txtDisplay.setEditable(false);
        txtDisplay.setLineWrap(true);
        txtDisplay.setWrapStyleWord(true);

        loadPosts();

        setLocationRelativeTo(null);
    }
    
    public ScrViewPosts(int friendID)
    {
        initComponents();

        this.friendID = friendID;

        txtDisplay.setEditable(false);
        txtDisplay.setLineWrap(true);
        txtDisplay.setWrapStyleWord(true);

        loadFriendPosts(friendID);

        setLocationRelativeTo(null);
    }
    
    
    private void loadPosts()
    {
        java.util.ArrayList<Post> list;

        if(myPosts == true)
        {
            list = AppData.getMyPosts();
        }
        else
        {
            list = AppData.getPublicPosts();
        }

        String output = "";

        for(int index = 0; index < list.size(); index++)
        {
            Post post = list.get(index);

            User user = AppData.findUserByID(post.getUserID());
            output += "============================\n";
            if(user != null)
            {
                output += "Posted By: "
                        + user.getFirstName()
                        + " "
                        + user.getSurname()
                        + "\n";
            }
            output += post.displayPost() + "\n\n";
            output += "Comments:\n";
            java.util.ArrayList<Comment> postComments =
                    AppData.getCommentsForPost(post.getPostID());

            for(int cIndex = 0; cIndex < postComments.size(); cIndex++)
            {
                Comment comment = postComments.get(cIndex);

                output += "- " + comment.displayComment() + "\n";
            }
            output += "============================\n\n";
        }

        txtDisplay.setText(output);
    }
    
    private void loadFriendPosts(int friendID)
    {
        java.util.ArrayList<Post> list = AppData.getFriendPosts(friendID);

        String output = "";

        User friend = AppData.findUserByID(friendID);

        if(friend != null)
        {
            output += "Posts by: "
                    + friend.getFirstName()
                    + " "
                    + friend.getSurname()
                    + "\n\n";
        }

        for(int index = 0; index < list.size(); index++)
        {
            Post post = list.get(index);

            output += "============================\n";
            output += post.displayPost() + "\n\n";

            output += "Comments:\n";

            java.util.ArrayList<Comment> comments = AppData.getCommentsForPost(post.getPostID());

            for(int cIndex = 0; cIndex < comments.size(); cIndex++)
            {
                Comment comment = comments.get(cIndex);
                output += "- " + comment.displayComment() + "\n";
            }

            output += "============================\n\n";
        }

        if(output.isEmpty())
        {
            output = "No posts found for this friend.";
        }

        txtDisplay.setText(output);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        txtPostID = new javax.swing.JTextField();
        txtComment = new javax.swing.JTextField();
        btnComment = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDisplay = new javax.swing.JTextArea();
        btnHelp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        txtComment.addActionListener(this::txtCommentActionPerformed);

        btnComment.setText("Add Comment");
        btnComment.addActionListener(this::btnCommentActionPerformed);

        txtDisplay.setColumns(20);
        txtDisplay.setRows(5);
        jScrollPane2.setViewportView(txtDisplay);

        btnHelp.setText("Help");
        btnHelp.addActionListener(this::btnHelpActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHelp))
                    .addComponent(txtComment, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComment)
                    .addComponent(txtPostID, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(txtPostID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtComment, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnComment)
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBack)
                            .addComponent(btnHelp)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        AppData.scrMainMenu = new ScrMainMenu();
        AppData.scrMainMenu.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommentActionPerformed
        // TODO add your handling code here:
        try
        {
            if(txtPostID.getText().isEmpty()
                    || txtComment.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Enter a post ID and comment.");
                return;
            }

            int postID = Integer.parseInt(txtPostID.getText());

            boolean postFound = false;

            for(int index = 0; index < AppData.posts.size(); index++)
            {
                Post post = AppData.posts.get(index);

                if(post.getPostID() == postID)
                {
                    postFound = true;
                }
            }

            if(postFound == false)
            {
                JOptionPane.showMessageDialog(this, "Post ID not found.");
                return;
            }

            AppData.addComment(postID, txtComment.getText());

            JOptionPane.showMessageDialog(this, "Comment added");

            txtComment.setText("");

            if(friendID == 0)
            {
                loadPosts();
            }
            else
            {
                loadFriendPosts(friendID);
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnCommentActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        // TODO add your handling code here:
        String helpText = "";
        helpText += "VIEW POSTS HELP\n\n";
        helpText += "Posts are displayed newest first.\n\n";
        helpText += "To add a comment:\n";
        helpText += "1. Enter a valid Post ID\n";
        helpText += "2. Enter your comment\n";
        helpText += "3. Click Add Comment\n\n";
        helpText += "Comments appear below posts.";
        JOptionPane.showMessageDialog(this, helpText);
    }//GEN-LAST:event_btnHelpActionPerformed

    private void txtCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ScrViewPosts(true).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnComment;
    private javax.swing.JButton btnHelp;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtComment;
    private javax.swing.JTextArea txtDisplay;
    private javax.swing.JTextField txtPostID;
    // End of variables declaration//GEN-END:variables
}
